/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_persuratan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author dheaardi
 */
public class backupdata extends javax.swing.JFrame {

    /**
     * Creates new form backupdata
     */
    public backupdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_backup_csv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_backup_csv.setText("Backup All Data");
        btn_backup_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backup_csvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_backup_csv, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_backup_csv)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backup_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backup_csvActionPerformed
        // TODO add your handling code here:
       try{
           String sql = "SELECT * FROM tbl_surat";
           java.sql.Connection conn = (Connection)koneksi.getKoneksi();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet res = stm.executeQuery(sql);
           
            String folderPath = "c:/backupdatasurat/";
            String baseFileName = "backup";
            String fileExtension = ".csv";
            String uniqueFileName = generateUniqueFileName(folderPath, baseFileName, fileExtension);
            String csvFilePath = folderPath + uniqueFileName;
            File folder = new File(folderPath);
            if (!folder.exists()) {
                folder.mkdirs();
            }
           
           FileWriter csvWriter = new FileWriter(csvFilePath);
           
           csvWriter.append("id,sifat_surat,no_surat,tgl_surat,type_surat,dari,kepada,perihal,deskripsi,file_surat");
           csvWriter.append("\n");
           
           while (res.next()) {
            // Replace "Column1Name", "Column2Name", etc. with actual column names
            csvWriter.append(res.getString("id")).append(",");
            csvWriter.append(res.getString("sifat_surat")).append(",");
            csvWriter.append(res.getString("no_surat")).append(",");
            csvWriter.append(res.getString("tgl_surat")).append(",");
            csvWriter.append(res.getString("type_surat")).append(",");
            csvWriter.append(res.getString("dari")).append(",");
            csvWriter.append(res.getString("kepada")).append(",");
            csvWriter.append(res.getString("perihal")).append(",");
            csvWriter.append(res.getString("deskripsi")).append(",");
            csvWriter.append(res.getString("file_surat")).append(",");
            // ... repeat for all columns
            
            csvWriter.append("\n");
        }
           csvWriter.flush();
           csvWriter.close();
        
           JOptionPane.showMessageDialog(this, "Sukses Backup Data!", "Success", JOptionPane.INFORMATION_MESSAGE);
       }catch(Exception e){
           e.printStackTrace();
       }
        
    }//GEN-LAST:event_btn_backup_csvActionPerformed
    private String generateUniqueFileName(String folderPath, String baseFileName, String fileExtension) {
    File folder = new File(folderPath);
    int index = 1;
    String uniqueFileName = baseFileName + fileExtension;
    
    while (new File(folder, uniqueFileName).exists()) {
        uniqueFileName = baseFileName + index + fileExtension;
        index++;
    }

    return uniqueFileName;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new backupdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backup_csv;
    // End of variables declaration//GEN-END:variables
}
