/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_persuratan;
import java.io.File;
import java.io.FileFilter;
import java.awt.Event;
import java.util.Calendar;
import java.awt.EventQueue;
import com.mysql.jdbc.Driver;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author galaxy.co
 */
public class SuratKeluar extends javax.swing.JFrame {
     public Statement st;
     public ResultSet rs;
     public String filename;
    /**
     * Creates new form NewJFrame
     */
    public SuratKeluar() {
        initComponents();
    }
    private void kosongkan(){
        itemSifat.setSelectedItem(null);
        txtNoSurat.setText(null);
        Date.setDate(null);
        txtFrom.setText(null);
        txtTo.setText(null);
        txtDeskripsi.setText(null);
        txtHal.setText(null);
        txtFileName.setText(null);
    
    }
    /**
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNoSurat = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        txtHal = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        txtFileName = new javax.swing.JTextField();
        itemSifat = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Date = new com.toedter.calendar.JDateChooser();
        BHome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MSuratMasuk = new javax.swing.JMenuItem();
        MSuratKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MAgendaSKeluar = new javax.swing.JMenuItem();
        MAgendaSMasuk = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setText("INPUT SURAT KELUAR");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel3.setText("No. Surat");

        jLabel4.setText("Dari");

        jLabel7.setText("Kepada");

        jLabel6.setText("Perihal");

        jLabel5.setText("Deskripsi");

        jLabel8.setText("File Surat");

        jLabel2.setText("Tanggal");

        jLabel9.setText("Sifat Surat");

        itemSifat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Penting", "- Rahasia" }));

        jButton1.setText("Pilih FIle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("TAMBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(itemSifat, 0, 194, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtFrom)
                            .addComponent(txtNoSurat))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHal)
                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(itemSifat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNoSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );

        BHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/skripsi_persuratan/img/home.png"))); // NOI18N
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });

        jMenu1.setText("Transaksi Surat");

        MSuratMasuk.setText("Surat Masuk");
        MSuratMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSuratMasukActionPerformed(evt);
            }
        });
        jMenu1.add(MSuratMasuk);

        MSuratKeluar.setText("Surat Keluar");
        MSuratKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSuratKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(MSuratKeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Data Surat");

        MAgendaSKeluar.setText("Data Sutrat Keluar");
        MAgendaSKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAgendaSKeluarActionPerformed(evt);
            }
        });
        jMenu2.add(MAgendaSKeluar);

        MAgendaSMasuk.setText("Data Surat Masuk");
        MAgendaSMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAgendaSMasukActionPerformed(evt);
            }
        });
        jMenu2.add(MAgendaSMasuk);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Action");

        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(BHome)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHome)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(778, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
        new HalamanUtama().show();
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_BHomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    FileFilter myfilter = new FileFilter() {
            
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".jpg")
                        || f.isDirectory();
            }

            public String getDescription() {
                return "JPG Files"; //type any description you want to display
            }
        };
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        this.filename = f.getAbsolutePath();
        String ext = filename.substring(filename.lastIndexOf('.')+1);
         Date tgl = Date.getDate();
        String nama = "Surat_dari";
        String dari = txtFrom.getText();
        int no = 0;
        String namaSurat = nama + dari + no +'.' + ext;
        no++;
        txtFileName.setText(namaSurat);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           String newpath = "src/upload";
           File directory = new File(newpath);
           
           if(!directory.exists()){
               directory.mkdirs();
           }
           File fileawal = null;
           File fileakhir = null;
           String ext = filename.substring(filename.lastIndexOf('.')+1);
           fileawal = new File(filename);
           fileakhir = new File(newpath+"/"+txtFileName.getText());
           String tampilan = "yyyy/MM/dd";
           SimpleDateFormat fm = new SimpleDateFormat(tampilan);
           String tanggal = String.valueOf(fm.format(Date.getDate()));
           Files.copy(fileawal.toPath(), fileakhir.toPath());
           
            if(txtNoSurat.getText()==null || Date.getDate() == null || txtFrom.getText() == null || txtTo.getText() == null || txtHal.getText() == null || txtFileName.getText() == null ){
                JOptionPane.showMessageDialog(null, "Pastikan Semua Data Terisi");
            }else{
                Integer id = 0;
                String sifat = itemSifat.getSelectedItem().toString();
                String noSurat = txtNoSurat.getText();
                String date = tanggal;
                Integer type = 2;
                String dari = txtFrom.getText();
                String kepada = txtTo.getText();
                String hal = txtHal.getText();
                String desk = txtDeskripsi.getText();
                String file = txtFileName.getText();
                
                String cek = "SELECT no_surat FROM tbl_surat";
                if(noSurat == cek){
                     JOptionPane.showMessageDialog(null, "No Surat sudah tersedia");
                }else{
                    String sql = "INSERT INTO tbl_surat VALUES('" + id + "','"+ sifat +"','"+ noSurat +"','"+ date +"','"+ type +"','"+ dari +"','"+ kepada+"','"+ hal +"','"+ desk +"','"+ file +"' )";
                 java.sql.Connection conn = (Connection)koneksi.getKoneksi();
                 java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                 pst.execute();
                 
                 JOptionPane.showMessageDialog(null, "berhasil simpan");
                 kosongkan();
                 
                }
                 
            }
    
        }catch(HeadlessException | SQLException e){
             JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (IOException ex) {
             Logger.getLogger(SuratKeluar.class.getName()).log(Level.SEVERE, null, ex);
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MSuratMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSuratMasukActionPerformed
        new SuratMasuk().show();
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_MSuratMasukActionPerformed

    private void MSuratKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSuratKeluarActionPerformed
        new SuratKeluar().show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MSuratKeluarActionPerformed

    private void MAgendaSKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAgendaSKeluarActionPerformed
        new AgendaSKeluar().show();
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_MAgendaSKeluarActionPerformed

    private void MAgendaSMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAgendaSMasukActionPerformed
        new Agenda().show();
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MAgendaSMasukActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int Logout=JOptionPane.showOptionDialog(this, "Keluar Aplikasi?", "Pesan Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,null,null);

        if(Logout==JOptionPane.YES_OPTION){
            new FormLogin().show();
            this.dispose();
        } // TODO add your handling        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuratKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuratKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHome;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JMenuItem MAgendaSKeluar;
    private javax.swing.JMenuItem MAgendaSMasuk;
    private javax.swing.JMenuItem MSuratKeluar;
    private javax.swing.JMenuItem MSuratMasuk;
    private javax.swing.JComboBox itemSifat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtHal;
    private javax.swing.JTextField txtNoSurat;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
